version: 2
jobs:
  build:
    
    working_directory: ~/java-api

    docker:
      - image: circleci/openjdk:8

    steps:

      - checkout
      
      - run: export TERM=${TERM:-dumb} && ./gradlew build --refresh-dependencies uploadArchives -PsonatypeUsername=$SONATYPE_USERNAME -PsonatypePassword=$SONATYPE_PASSWORD
      
      - store_test_results:
          path: build/reports